name: Compose CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  compose:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    env:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${{ 'home_office_store' }}
      DB_USER: ${{ 'postgres' }}
      DB_PASSWORD: ${{ 'postgres' }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ARGOCD_PAT }}
          repository: IliaDiv/hos-argocd
          event-type: change-sha
          client-payload: '{"sha": "${{ github.sha }}"}'



