name: Compose CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  compose:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ARGOCD_PAT }}
          repository: IliaDiv/hos-argocd
          event-type: change-sha
          github_sha_hash: ${{ github.sha }}
          github_sha_short: "${github_sha_hash:0:6}"
          client-payload: '{"sha": "${github.sha_short}"}'




